<?php
/**
 * @file node/content.inc
 */

class LanggoNodeBasicContentBlogMigration extends LanggoNodeBasic {
  protected $bundle = 'blog';
}

class LanggoNodeBasicContentBookMigration extends LanggoNodeBasic {
  protected $bundle = 'book';
}

class LanggoNodeBasicContentLessonMigration extends LanggoNodeBasic {
  protected $bundle = 'lesson';
}

class LanggoNodeBasicContentPersonalLessonMigration extends LanggoNodeBasic {
  protected $bundle = 'personal_lesson';
}

class LanggoNodeBasicContentExerciseMigration extends LanggoNodeBasic {
  protected $bundle = 'exercise';
}

class LanggoNodeBasicContentAQuestionMigration extends LanggoNodeBasic {
  protected $bundle = 'aquestion';
}

class LanggoNodeBasicContentWiziqMigration extends LanggoNodeBasic {
  protected $bundle = 'wiziq';
}

class LanggoNodeBasicContentMassContactMigration extends LanggoNodeBasic {
  protected $bundle = 'mass_contact';
}

class LanggoNodeBasicContentLessonSourceMigration extends LanggoNodeBasic {
  protected $bundle = 'lesson_source';
}

class LanggoNodeBasicContentPageMigration extends LanggoNodeBasic {
  protected $bundle = 'Page';
}

class LanggoNodeBasicContentPronunciationMigration extends LanggoNodeBasic {
  protected $bundle = 'pronunciation';
}

class LanggoNodeBasicContentLanggoHelpMigration extends LanggoNodeBasic {
  protected $bundle = 'langgo_help';
}

class LanggoNodeBasicContentTestimonialMigration extends LanggoNodeBasic {
  protected $bundle = 'testimonial';
}

class LanggoNodeBasicContentSkillGrammarMigration extends LanggoNodeBasic {
  protected $bundle = 'skill_grammar';
}

class LanggoNodeBasicContentWebformMigration extends LanggoNodeBasic {
  protected $bundle = 'webform';
}

class LanggoNodeBasicContentWorkshopMigration extends LanggoNodeBasic {
  protected $bundle = 'workshop';
}

class LanggoNodeBasicContentLearningTripMigration extends LanggoNodeBasic {
  protected $bundle = 'learning_tip';
}

class LanggoNodeBasicContentLessonGroupMigration extends LanggoNodeBasic {
  protected $bundle = 'lesson_group';
}

# course
# extend_course
# poll
